/* ══════════ LEADERSHIP REDEFINED · COURSE ONE · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus short clips
   for stops, cards, and situations. Every page script follows the same adult
   learning arc (Knowles; Mayer):
     1. Breadcrumb back: where you are and how it connects to the last page.
     2. Why it matters to you: the problem it helps you solve this month.
     3. Teach: the idea in plain words, with one concrete example.
     4. Your experience: a prompt to connect it to your own work.
     5. Do: what to do on this page, and what you will get from it.
     6. Breadcrumb forward: what comes next.
   Played from ../assets/audio/course-one/<key with / as ->.mp3; the browser's
   voice reads the same words if a clip is missing. Names are spelled as they
   are said (Diermeier is written Deer-myer); the screen keeps the real
   spelling. No em or en dashes. */
window.LR_NARR = {
  /* ── WELCOME ── */
  'home/1': 'Welcome to Course One of Leadership Redefined. At the Symposium, you heard the big ideas. Over the next seventy minutes or so, you will put three of them to work on a real problem: your pod’s capstone. Here is why that matters. By November twentieth, your pod will hand a panel of judges a three-page brief that names a challenge for Vanderbilt and solves it. Everything in this course is built to help you write the first page of that brief, the page that makes the case. You bring years of experience leading people and work at Vanderbilt. This course will not lecture you about leadership in general. It gives you a few sharp tools, asks you to try each one, and then asks you to use it on your own pod’s idea. There are four lessons: vision and strategy, story and brand, mission and margin, and then your brief. Each page has one idea and one thing to do. You can listen, read along, or both, and you can go in any order. Your answers save in this browser and print as a weekly takeaway. Plan to finish by Friday, November sixth. When you are ready, tap Start Course One.',

  /* ── LESSON 1 · VISION AND STRATEGY ── */
  'route/1': 'This first page is your map. Before you start any learning, it helps to know where you are going and why, so here is the shape of the week. Lesson one is vision and strategy: what the Chancellor’s vision asks of you, and a test for telling strategic work from busy work. Lesson two is story and brand: how Vanderbilt thinks about its reputation, and how to tell your pod’s story so people want to act. Lesson three is mission and margin: how leaders weigh purpose and money in the same decision. Lesson four is your brief: you choose a focus area and draft the first three sections. Each lesson ends with a short wrap-up where you put the ideas in your own words. That step matters. Explaining something back is one of the most reliable ways adults remember what they learn. Tap each stop to preview it. Then turn the page, and we will start with the vision itself.',
  'route/g1': 'Stop one, vision and strategy. You will see the vision and its three areas of focus, learn how reputation and resources feed each other, guess four numbers that show whether the strategy is working, tour four growth sites, and sort six real-sounding initiatives with a tool called the value stick.',
  'route/g2': 'Stop two, story and brand. A short video from the Chancellor on effective communication, the difference between brand and reputation, your part in the ground game, and then you draft your pod’s storyline.',
  'route/g3': 'Stop three, mission and margin. The Chancellor again, two hard calls about money and purpose, and how to count the whole cost of a decision, from his book Mission and Margin.',
  'route/g4': 'Stop four, your brief. Practice choosing a focus area, draft sections one to three, and check what you can now apply.',

  'mission/1': 'You just saw the map. Now the starting point for everything else: the vision. Vanderbilt will define the great university of the twenty-first century, and be it. Notice the second half. The vision is not to be admired; it is to be built, by people like you. It has a partner sentence: Vanderbilt will help reclaim the essential role of leading research universities in driving American prosperity. And it comes with a how: uncommon speed, agility, and scale. Speed means deciding and delivering faster than peers. Agility means changing course when conditions change. Scale means building things that reach many people. The work happens in three areas of focus, and here is why you need to know them cold: your capstone brief must choose one, and it is judged only against other briefs in that same area. Think for a moment about your own unit. Which of these three does most of your team’s work serve? Tap each area of focus to read it in full. Next, we look at the problems this vision was written to solve.',
  'mission/f1': 'Exceptional Core Operations. Running Vanderbilt so well, with speed, agility, and scale, that the university has the talent, resources, and reputation to deliver on the vision. Think of core operations as the fuel. If your pod’s idea makes existing work faster, cheaper, or better, this is your area.',
  'mission/f2': 'Bold Strategic Initiatives. With excellent core operations as the fuel, Vanderbilt pursues bigger bets that extend the reach of its education and research. If your idea creates something new, this is your area.',
  'mission/f3': 'Values Leadership. A commitment to shared values that guide everything Vanderbilt does, especially open forums, institutional neutrality, and civil discourse. By modeling what an essential research university stands for, Vanderbilt protects its mission. If your idea is about what Vanderbilt stands for, this is your area.',

  'problems/1': 'On the last page you met the vision. Here is a way to understand it more deeply: every strategy is an answer to a problem. If you know the problem, the strategy makes sense. In his strategy presentation to this program, Chancellor Deer-myer named four problems facing America’s leading research universities. First, they lack the capabilities to innovate at the speed and scale the world now needs. Second, they are no longer seen as the people who solve real problems. Third, elite universities are seen as politicized. And fourth, a university degree is no longer seen as essential to the American dream. Now read the vision against them. Uncommon speed answers the first. Bold initiatives answer the second. Values leadership answers the third. And the student experience answers the fourth. Here is why this helps you: when your pod writes why your challenge matters, tying it to one of these four problems makes the case instantly. Think of a frustration in your own work. Which problem is it a small version of? Tap each card to see where you meet it. Next, the engine that connects reputation to the resources Vanderbilt needs.',
  'problems/f1': 'Speed and scale. Good ideas die in approval queues and handoffs. You meet this problem in any process you own that takes weeks when it could take days.',
  'problems/f2': 'Relevance. People do not automatically connect a university’s work to their own lives. You meet it every time your team can show a result that someone off campus would care about.',
  'problems/f3': 'Trust. Many people doubt that universities welcome every point of view. Vanderbilt’s commitment to open forums, institutional neutrality, and civil discourse is the answer, and you practice it in how you run meetings and make decisions.',
  'problems/f4': 'The value of a degree. Families want proof that the cost is worth it. You meet it in anything that shapes a student’s experience or outcome, from advising to the speed of a financial aid answer.',

  'engine/1': 'On the last page you saw the four problems the vision answers. Now the mechanism the Chancellor uses to explain how Vanderbilt gains ground: the reputation feedback loop. It works like an engine with three parts. Reputation attracts resources: talent, funding, partnerships, and access and influence. Resources produce results: stronger students, better research, better care and service. And results build reputation, which attracts more resources, so the loop turns faster. Notice that it runs in reverse too. One public failure costs talent and funding. Three flywheels speed the engine up. Execution with ambition means doing big things, and doing them well. Values-driven leadership means open forums, institutional neutrality, and civil discourse, so people trust Vanderbilt to hear every view. Athletics momentum means attention that turns into affinity, often from people who never read a research paper. Here is why this matters to you: staff leaders turn the first flywheel every day. Think of a moment when your team delivered something big, on time. Who noticed, and what did they tell others? Now sort six moments by the flywheel each one turns, and read the explanation after each. Next, the numbers that show whether the engine is running.',
  'numbers/1': 'You just learned the reputation engine. Now, is it running? Before you see the numbers, you will guess them. That is deliberate. Research on what is called the pretesting effect shows that making a guess first, even a wrong one, makes the real answer stick far better than simply reading it. So commit to a guess on each tile. Then read each number as one turn of the loop. Media mentions are attention. Early Decision applications are talent choosing Vanderbilt first. New gifts and pledges are funding. New campuses are reach. All four rose together, which is what an engine turning faster looks like. As you guess, ask yourself which part of the loop your own team feeds. Next, where those new campuses are, and what they ask of the rest of us.',
  'growth/1': 'The last tile said four growth sites. Here they are on the map the Chancellor showed, because a strategy becomes real when it has an address. Each one is a Bold Strategic Initiative, the second area of focus. Three things make an initiative bold. It extends reach: new learners, new partners, and new places, in fields like technology, business, and research. It is a bet: it accepts risk for a bigger return to the mission, and it is judged by results, not announcements. And it runs on core operations: a campus opens only if hiring, IT, finance, facilities, and student services work at speed in a new city. That last point is where most of this cohort comes in. Every new site needs the back office Nashville already has. Think about your own unit. If a colleague started work at a new campus tomorrow, what would they need from your team on day one, and how long would it take? Tap each growth site on the map to see what it is, and where you meet it. Next, a tool for deciding which work is truly strategic.',
  'growth/f1': 'Vanderbilt N Y C. Vanderbilt’s first campus beyond Nashville, open since August twenty twenty six: thirteen buildings on two point seven acres in Chelsea, with an undergraduate semester program and a master’s in business and technology. You meet it in any service a student or colleague in New York needs from Nashville.',
  'growth/f2': 'Vanderbilt West Palm Beach. A graduate campus for business, engineering, data science, and A I, with programs planned in finance and in space and defense technology: about one thousand graduate students and one hundred faculty. You meet it in the programs, hiring, and systems built for a second home.',
  'growth/f3': 'Vanderbilt San Francisco. It opens for the twenty twenty seven to twenty twenty eight school year on the California College of the Arts campus, home to a college that blends art and design with engineering and A I: about one thousand students. You meet it in partnerships with the technology and creative sectors.',
  'growth/f4': 'Quantum Innovation in Chattanooga. The Institute for Quantum Innovation, launched with E P B in July twenty twenty six: about two hundred fifty researchers, faculty, and staff, working with the first site in the country with commercial access to both a trapped-ion quantum computer and a quantum network. You meet it in research administration and in partnerships across Tennessee.',

  'valuestick/1': 'The growth sites showed where the big bets are. Now a practical question every leader faces: of all the work on your plate, which of it is actually strategic? The program’s pre-work, Felix Oberholzer-Gee’s book Better, Simpler Strategy, offers a simple test called the value stick. Picture a vertical stick. At the top is willingness to pay: the most someone would give for what you offer. In a university, paying usually means choosing Vanderbilt, giving more, bringing a grant, or partnering with us. At the bottom is willingness to sell: the least a colleague or supplier would accept to work with us. Meaningful work, good tools, and growth lower it. The space between the two is the value Vanderbilt creates. Strategy widens that space, by raising the top or lowering the bottom. Work that moves neither is activity, however busy it feels. Here is the one question to carry with you: whose choice changes, and which way? Think of the last project you finished. Whose choice did it change? Now sort six initiatives, and read the explanation after each one. Next, what lesson one means for you: for your capstone, and as a manager.',

  'me1/1': 'Lesson one gave you the vision, the reputation engine, and the value stick. Here is what they mean for you, in two places. For your capstone: name one focus area and tie your challenge to one of the four problems; that is your why it matters. Run the value stick on your idea and say whose choice it changes. And show which resource it grows: talent, funding, partnerships, or access. As a manager, the same tools work on Monday morning. Translate the vision for your team in one sentence. Run the value stick on your project list, and stop one thing that is only activity. And make speed visible: pick one process that takes weeks and set a target in days. Think about your own team. Which of these would change the most? Write the one thing you will try in the next two weeks. Next, a short wrap-up for lesson one.',
  'recap1/1': 'That is lesson one. Before moving on, let us lock it in. Three ideas. First, the vision is an instruction: define the great university of the twenty-first century, and be it, through uncommon speed, agility, and scale, in three areas of focus. Second, reputation is an engine: reputation brings resources, resources produce results, and results build reputation, with three flywheels speeding it up. Attention, applications, gifts, and four growth sites show it running. Third, strategy is a choice: work is strategic only when it raises what people will give or lowers what it costs them to stay. Now the most important step on this page. Pick one thing your team actually does, and write two sentences. Whose choice does it change, and which area of focus does it serve? Do not skip this. Putting an idea in your own words, about your own work, is how it moves from something you read to something you use. Your answer saves here and prints in your takeaway. Next, lesson two: how Vanderbilt tells its story, and how your pod will tell yours.',

  /* ── LESSON 2 · STORY AND BRAND ── */
  'brand/1': 'Welcome to lesson two. In lesson one you saw that reputation brings resources. This lesson is about how reputation is built, and the part you play. Start with the short video from Chancellor Deer-myer on effective communication. Then one distinction from Vice Chancellor Steve Ertel, who leads communications and marketing. Brand is what you say about yourself. It is owned: values, campaigns, messages. Reputation is what others say about you. It is earned: news stories, rankings, word of mouth. They are separate but related, and the goal is to close the gap between them. The gap grows when the experience does not match the claim. You close it by delivering the claim, then telling true stories about it. Vanderbilt’s own read of its brand is candid: strong in the South, less known nationally, often seen as similar to peers, and facing a wider doubt about higher education. Think about what a student or a vendor would say about your office. Is it the same as what your website says? Now decide six statements: brand, or reputation? Next, how a single big moment becomes lasting trust.',

  'fighter/1': 'You just separated brand from reputation. Now the question is how reputation grows. Vice Chancellor Ertel calls Vanderbilt a fighter brand: not the loudest, deeply valued once discovered. People who know Vanderbilt love it; not enough people know it yet. That changes how you earn attention. People move up a ladder: first relevance, then consideration, then trust, then commitment. A spike moment, like an upset win or a major gift, puts Vanderbilt on the first rung. But a spike without a system is noise. Attention fades unless a steady drumbeat of stories keeps people climbing. Big campaigns and national media are the air cover; they create stories, speeches, and coverage. The ground game is leaders carrying those stories directly to the people who matter: government, donors, business, prospective parents. And those people pass them on, because trust travels through proximity. That makes you part of the ground game. Think of one person outside Vanderbilt who trusts your work. How did that trust start? Tap the four moves a fighter brand makes. Next, your part in it: the ground game.',
  'fighter/f1': 'Earn attention thoughtfully. A fighter brand cannot outshout bigger names, so it chooses where to show up. From your seat, reach the two or three audiences your work matters to most, and reach them well.',
  'fighter/f2': 'Interrupt expectation. People expect a university to be slow and cautious. Surprise them. The three-day answer when they expected three weeks becomes a story they repeat.',
  'fighter/f3': 'Design bold moments. Spike moments give people a reason to look closer. In the Chancellor’s words, a little controversy is good for us. Treat a difficult topic as a chance to engage, not a thing to avoid.',
  'fighter/f4': 'Sustain meaning over time. Reputation works as infrastructure, a system rather than a campaign. Keep telling the same true story long after the launch.',

  'ground/1': 'You just saw that a spike needs a system. Here is who runs that system: you. Vice Chancellor Ertel put it this way. Reputation creates resources when air cover is carried through ground game. Air cover is campaigns, advertising, and media. The ground game is leaders carrying the story person to person. He also said brands come to exist in one of two ways: by default, when we let the world tell our story, or by design, when we tell our own. The ground game works in three steps. First, reputation assets are created: stories, speeches, earned media, paid media, and social media. Second, those assets are shared directly with priority stakeholders and influencers: government, donors, business, and prospective parents. Third, the impact is multiplied peer to peer, because trust travels through proximity. The people you reach tell people you never will. So what can you do? Understand what sets Vanderbilt apart. Share reputation assets with the people you work with. Equip others to tell the story. And treat difficult or controversial topics as a chance to engage, not a reason to go quiet. Think of one result your team delivered this year that someone outside your office should hear about. Who is that person? Now plan one play of your ground game. It saves here and prints in your takeaway. Next, you will tell your pod’s story.',
  'story/1': 'You have planned how to carry a story. Now you will build the story your pod will tell the judges, and later a sponsor. The pre-work for this topic is Nancy Duarte’s talk on the structure of great talks. Her finding: great communicators keep moving between two places. What is, the frustrating present. And what could be, a better future. The gap between them creates tension, and tension makes people lean in. Then the speaker ends with one clear call to action and a picture of life after people act. Three moves, then. Open with what is, through one real person and one real moment. Contrast it with what could be, and go back and forth. End with one ask, and name what each audience gets: a dean wants research time, a finance leader wants the cost, a student wants the experience. The strongest pods in past cohorts opened with one person, not a statistic. Think of the last presentation that actually changed your mind. Chances are it started with a person, not a chart. If you are unsure what good looks like, open the strong example before you write. Then draft your storyline. It saves here and folds into your brief later. Next, what lesson two means for you: for your capstone, and as a manager.',

  'me2/1': 'Lesson two was about brand, reputation, and story. Here is what it means for you. For your capstone: open your brief with one real person and one real moment, then move between what is and what could be. Name your audiences and what each one cares about. And plan the ground game: who carries your story after the judging. As a manager: close your unit’s gap between what you claim and what people actually experience, and fix the experience first. Build a drumbeat, one short, true story about your team’s work every month. And equip your team to tell Vanderbilt’s story, including when the topic is hard. Think about the last story someone told about your team. Was it the one you would have chosen? Write the one thing you will try in the next two weeks. Next, a short wrap-up for lesson two.',
  'recap2/1': 'That is lesson two. Three ideas to keep. Close the gap: brand is what we say about ourselves, reputation is what others say about us, and the gap closes when we deliver the claim and then tell true stories. A spike needs a system: attention climbs from relevance to consideration to trust to commitment only with a steady drumbeat, carried by leaders on the ground. And tell it as what could be: one real person, the contrast between the present and a better future, and one clear ask. Now apply it to your pod. Write down which audience matters most for your idea, and the one sentence of what could be that they need to hear. That sentence may end up opening your brief. Next, lesson three: the hard trade-offs between purpose and money.',

  /* ── LESSON 3 · MISSION AND MARGIN ── */
  'margin/1': 'Welcome to lesson three. Your story says why your idea matters. This lesson answers the question every judge and sponsor will ask next: can Vanderbilt afford it, and is it worth it? Start with the Chancellor’s video. Then hold on to three ideas. Mission is purpose: research, teaching, and discovery. Margin is capacity: the financial strength to pursue the mission. They feed each other, which is why a leader owns both. The Chancellor describes a leadership mindset: steward purpose and performance together, use mission to set priorities, build trust by being transparent and consistent, and think long term while naming the trade-offs. And four practical levers: know where money comes from and where it goes, use data and discipline, partner academic and finance leaders, and pilot, learn, and scale. Here is why it matters now. In twenty twenty five, many peer universities announced layoffs and hiring freezes. On the Chancellor’s comparison chart, Vanderbilt had none of those actions marked. Discipline in good years bought choices in hard ones. Think of a hard budget call you have made. Now try two situations, and test the other answers too, to see what they would cost. Next, how to count the whole cost of a decision.',
  'margin/s1': 'Situation one. A small program does real good for forty students a year, at three times the usual cost per student, and your budget is flat. What would you do? Choose first, then read the consequence.',
  'margin/s2': 'Situation two. An outside partner offers good money to use your space and staff time for something unrelated to your mission. It would fund two positions. What would you do?',

  'portfolio/1': 'You just made two hard calls. Now a habit that makes every call better: counting the whole cost. This lesson draws on Mission and Margin, the practical guide to university finances that Chancellor Deer-myer wrote with Brett Sweet, Vanderbilt’s chief financial officer. Its first idea is its first chapter: no margin, no mission. Margin is the capacity that makes the mission possible, so every decision has a financial side, even when it starts as an academic one. The book then walks through where that side hides. Follow the cash: when money actually arrives and leaves, not only what the budget line says. Buildings: a building costs money every year it stands, through upkeep and depreciation. Space: it is a resource with a cost, not a free extra. Research: it costs more than its direct grant dollars. Scholarships and fundraising: they deserve the same financial analysis as any other commitment. And debt: borrowing for a big project carries costs and limits for years. Here is an example. A donor funds a new lab. The gift covers construction. The whole cost also includes decades of maintenance, the space it occupies, and the research it is meant to house. Think of something your unit said yes to in the last few years. What did it cost in year three? Now find the hidden cost in six decisions, and read why after each. Next, you will write your pod’s mission and margin statement.',

  'statement/1': 'You have counted the whole cost. Now make your pod’s case before anyone asks. Every judge will ask two questions of your brief: does it serve the mission, and can Vanderbilt afford to keep it going? A strong statement answers both in about four sentences. It names a specific mission benefit, not a general one. It names the cost and where the money comes from, and reallocating an existing budget counts. It names the return, whether that is time saved, revenue, or a risk avoided. And it counts the whole cost: what the idea costs after year one, and who pays. Think about the last budget request you saw approved quickly. It probably answered all four. If you are unsure, open the strong example first, then write your own. One more tip from past cohorts: the pods that impressed judges named their funding source plainly. One funded its idea from event budgets departments already had. Next, what lesson three means for you: for your capstone, and as a manager.',

  'me3/1': 'Lesson three was about mission and margin. Here is what it means for you. For your capstone: state the mission benefit in specifics, then the cost and where the money comes from. Count the whole cost, what your idea costs after year one, including when the cash moves, the space, and the upkeep. And bring a finance partner in early. As a manager: know your unit’s money, where it comes from and where it goes. Talk about trade-offs openly with your team; transparency and consistency build trust, even when the answer is no. And before any yes, ask two questions: what will it cost in year three, and what will we stop? Think about your team’s last new commitment. Did anyone ask about year three? Write the one thing you will try in the next two weeks. Next, a short wrap-up for lesson three.',
  'recap3/1': 'That is lesson three. Three ideas. No margin, no mission: mission is purpose, margin is capacity, and a leader stewards both. Count the whole cost: follow the cash, and count buildings, space, research costs, and debt past year one. Answer both questions: every proposal names its mission benefit, its cost and where the money comes from, and its return. Now apply it to your own pod’s idea. What will it cost after year one, and what would pay for it? If you cannot answer that yet, write down the question. It is a good one to bring to your pod. Next, lesson four: your brief.',

  /* ── LESSON 4 · YOUR BRIEF ── */
  'focus/1': 'Welcome to lesson four. Everything so far has been preparation for this. Your pod submits one brief, no longer than three pages, due Friday, November twentieth. It has seven parts. This week you draft the first three: your focus area, the challenge and why it matters strategically, and the connection to Vanderbilt’s priorities. Next week, Course Two covers the rest. Start with the focus area, because it decides who you compete against. Three winners will be named, one per area. Here is a quick way to choose. If your solution makes existing work faster, cheaper, or better, it is Core Operations. If it creates something new that extends education or research, it is a Bold Initiative. If it shows what Vanderbilt stands for, it is Values Leadership. Many ideas touch two. Choose the area where your solution does most of its work, and choose it on purpose. Think about your pod\u2019s idea right now: if a judge asked which area it belongs in, could you answer in one sentence? Practice with five challenges, then read why after each. Next, you draft.',

  'draft/1': 'You have chosen a focus area. Now write the page that makes your case. Notice what you already have: your storyline from lesson two and your mission and margin statement from lesson three fold into this draft automatically. That is by design. You have been building this page all along. Four parts. Your focus area, at the very top. The challenge, in one sentence: who is affected, and what happens today. Why it matters strategically: what it costs to wait, in mission, money, people, or reputation. Tie it to one of the four problems from lesson one if you can. And the connection to Vanderbilt’s priorities, by name: the line from the vision and the area of focus it serves. Open the example to see what strong looks like, and read what a judge will ask. Then ask yourself: could a colleague outside your office read your challenge sentence and explain the problem back to you? Then write your version. Copy it into your pod’s shared document before you meet. Next, eight short situations to check what you can apply.',

  'quiz/1': 'You have learned the ideas and used them on your own work. Now check whether you can apply them to situations you have not seen yet. That is the real test of learning, and it is why these are scenarios, not definitions. Eight short situations. Choose what you would do, then read the explanation, which names the idea behind the best answer. Six of eight completes the check. If you miss one, the explanation will point you back to the page to revisit, and you can retake it anytime. Next, your moves for the week.',

  'nextstep/1': 'You are nearly done with Course One. Learning sticks when it turns into action in the next few days, so this page turns the course into four moves. Meet your pod for about forty five minutes and agree on one challenge and one focus area. Put your draft and your storyline in the pod’s shared document. Post in your cohort’s Teams channel on this week’s topic, and reply to at least one colleague; a starter post is ready to copy, built from what you wrote. Tap each move to commit. There is also a pod meeting agenda you can copy, and you can print this week’s takeaway: your overview, every activity, your answers, and your drafts in one place. Aim to finish by Friday, November sixth. Next, a short close.',

  'learn/1': 'That is Course One. Look at what you have now: a clear view of the strategy, a story your pod can tell, a case in both mission and money, and a first draft of page one of your brief. Take it to your pod. Course Two opens the week of November ninth, with entrepreneurial mindset, reputational stewardship, and high-performing teams, and it helps you draft the rest of the brief. Crescere aude. Dare to grow.'
};
