/* ══════════ LEADERSHIP REDEFINED · COURSE ONE · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus one short
   clip per stop, area of focus, problem, move, and situation. The Listen
   button plays ../assets/audio/course-one/<key with / as ->.mp3 and falls
   back to the browser's speech synthesis when a clip is missing. Names are
   spelled as they are said (Diermeier is written Deer-myer); the screen
   keeps the real spelling. No em or en dashes. */
window.LR_NARR = {
  'home/1': 'Welcome to Course One of Leadership Redefined. The Symposium gave you the ideas. This week, the week of November second, puts three of them to work: vision, strategy, and the future of Vanderbilt; communication, storytelling, and brand; and mission and margin. It takes about forty five minutes, in four short lessons, and it is entirely self-paced. Finish by Sunday, November eighth. Every page has one idea and one thing to do, and everything you write here becomes part of your pod’s capstone brief. Turn pages with the arrows at the bottom right, and tap Listen on any page to hear it again. When you are ready, tap Start Course One.',
  'route/1': 'Here is the week in four stops. First, vision and strategy: what the Chancellor’s vision asks of you, and a simple test for telling strategy from busy work. Second, story and brand: the Chancellor on effective communication, and the storyline your pod will tell. Third, mission and margin: the Chancellor again, and the trade-offs every leader makes between purpose and money. And fourth, your brief: pick your focus area and draft the first three sections. Tap each stop to preview it.',
  'route/g1': 'Stop one, vision and strategy. You will open the three areas of focus, guess four numbers that show the strategy is working, and sort six initiatives with the value stick.',
  'route/g2': 'Stop two, story and brand. Start with a short video from the Chancellor on effective communication, then decide what counts as brand and what counts as reputation, and draft your pod’s storyline.',
  'route/g3': 'Stop three, mission and margin. The Chancellor explains why the two belong together. Then you make two hard calls and balance a portfolio of five activities.',
  'route/g4': 'Stop four, your brief. Practice choosing a focus area, draft sections one to three, take a five-question check, and commit to your moves for the week.',
  'mission/1': 'Everything in this program starts with one sentence. Vanderbilt will define the great university of the twenty-first century, and be it. The way there is to operate at uncommon speed, agility, and scale. And there are three areas of focus. These matter twice for you this month, because your capstone brief must choose one of them, and it is judged only against other briefs in that same area. Tap each area of focus to read it in full.',
  'mission/f1': 'Exceptional Core Operations. Running Vanderbilt so well, with speed, agility, and scale, that we have the talent, resources, and reputation to deliver on the vision. If your pod’s challenge is about how the work gets done, this is your area.',
  'mission/f2': 'Bold Strategic Initiatives. With excellent core operations as the fuel, Vanderbilt pursues bigger bets that extend the reach and impact of education and research. If your idea is something new, this is your area.',
  'mission/f3': 'Values Leadership. Modeling the role of an essential research university, and advocating for it, to change the wider sector and defend the mission. If your idea is about what Vanderbilt stands for, this is your area.',
  'problems/1': 'A strategy is an answer to a problem. In his strategy presentation to this program, Chancellor Deer-myer named four problems facing America’s leading research universities. They lack the capabilities to innovate at the speed and scale the world needs. They are no longer seen as the people who solve real problems. Elite universities are seen as politicized. And a university degree is no longer seen as essential to the American dream. He also said, our mission is not small; we are scaling Mount Everest. Tap each problem to see where you meet it in your own work. Your pod’s challenge probably touches at least one.',
  'problems/f1': 'Speed and scale. Good ideas die in approval queues and handoffs. You meet this problem in any process you own that takes weeks when it could take days.',
  'problems/f2': 'Relevance. People do not automatically connect a university’s work to their own lives. You meet it every time your team can show a result that someone off campus would care about.',
  'problems/f3': 'Trust. Many people doubt that universities welcome every point of view. Vanderbilt’s commitment to open forums, institutional neutrality, and civil discourse is the answer, and you practice it in how you run meetings and decisions.',
  'problems/f4': 'The value of a degree. Families want proof that the cost is worth it. You meet it in anything that shapes a student’s experience or outcome, from advising to the speed of a financial aid answer.',
  'numbers/1': 'Is the strategy working? The Chancellor answered with trend lines, not adjectives. Before you see the numbers, guess them. Research on the pretesting effect shows that guessing first makes the answer stick. Tap a tile, make your guess, and then read the real number and what it means. These four come from the reputation loop: attention, applications, gifts, and growth.',
  'valuestick/1': 'Now, a simple test for strategy, from the program’s pre-work, Felix Oberholzer-Gee’s book Better, Simpler Strategy. Picture a stick. At the top is willingness to pay: the most a student, family, donor, or partner would give for what Vanderbilt offers. In a university, paying often means choosing Vanderbilt, giving more, or bringing a grant. At the bottom is willingness to sell: the least a colleague or supplier would accept to work with us. The space between is the value we create. Strategic work either raises willingness to pay or lowers willingness to sell. Everything else is activity. Sort six initiatives, one at a time.',
  'brand/1': 'Lesson two, story and brand. Start with a short video from Chancellor Deer-myer on effective communication. Then one distinction from Vice Chancellor Steve Ertel, who leads communications and marketing. Brand is what you say about yourself. Reputation is what others say about you. They are separate but related, and the goal is to close the gap between them. Vanderbilt’s own read is candid: strong in the South, less known nationally, and fighting a wider devaluation of higher education. Brands exist by default or by design. We can let the world tell our story, or we can tell our own. Decide six statements: brand, or reputation?',
  'fighter/1': 'Vice Chancellor Ertel calls Vanderbilt a fighter brand. Not the loudest. Deeply valued once discovered. High affinity, low saliency: people who know Vanderbilt love it, and not enough people know it yet. A big moment, like beating the number one team in the country, creates a spike in attention. But a spike without a system is noise. It fades unless a steady drumbeat of stories carries it. Relevance comes before consideration, consideration before trust, and trust before commitment. Big campaigns are the air cover. The ground game is people like you carrying stories to the people who matter, because trust travels through proximity. Tap the four moves a fighter brand makes.',
  'fighter/f1': 'Earn attention thoughtfully. A fighter brand cannot outshout bigger names, so it chooses where to show up. From your seat, reach the two or three audiences your work matters to most, and reach them well.',
  'fighter/f2': 'Interrupt expectation. People expect a university to be slow and cautious. Surprise them. The three-day answer when they expected three weeks becomes a story they repeat.',
  'fighter/f3': 'Design bold moments. Spike moments give people a reason to look closer. In the Chancellor’s words, a little controversy is good for us. Treat a difficult topic as a chance to engage, not a thing to avoid.',
  'fighter/f4': 'Sustain meaning over time. Reputation works as infrastructure: a system, not a campaign. Keep telling the same true story long after the launch.',
  'story/1': 'Now the craft. The program’s pre-work for this topic is Nancy Duarte’s talk on the secret structure of great talks. Great communicators keep moving between what is, the frustrating present, and what could be, the better future. The gap between them creates the tension that makes people lean in. Then they end with one clear call to action. The strongest capstone pods in past cohorts opened with one real person and one real moment. A name and a moment beat a percentage. Draft your pod’s storyline: the person, what is, what could be, the ask, and the audiences who need to hear it, with what each one cares about. It saves in this browser, and it folds into your brief draft in lesson four.',
  'margin/1': 'Lesson three, mission and margin. Start with the Chancellor. Then hold on to three ideas. Mission is purpose: research, teaching, and discovery. Margin is capacity: the financial strength to pursue the mission. And building financial capacity is everybody’s job. In twenty twenty five, peer universities announced layoffs, hiring freezes, and budget cuts. Vanderbilt’s discipline in good years bought it choices in hard ones. The leadership mindset is to steward both purpose and performance, use mission to set priorities, build trust through transparency, and think long term. Now two situations. Choose what you would do, then try the others to see what they would cost.',
  'margin/s1': 'Situation one. A small program does real good for forty students a year, at three times the usual cost per student, and your budget is flat. What do you do?',
  'margin/s2': 'Situation two. An outside partner offers good money to use your space and staff time for something unrelated to your mission. It would fund two positions. What do you do?',
  'portfolio/1': 'Here is a tool for seeing trade-offs at a glance: the mission and margin matrix. Up is mission impact. Right is financial contribution. Stars are high on both, so you invest. Hearts are high in mission but cost money, so you keep them and name what pays for them. Money Trees earn money with little mission tie, so you harvest them on purpose. Stop Signs are low on both. You lead a unit with five activities and one hundred points to invest. Move the sliders and watch the gold dot show where your portfolio lands. There is no single right answer. The read tells you what your choice implies.',
  'statement/1': 'Every judge will ask two questions of your brief. Does it serve the mission? And can Vanderbilt afford to keep it going? Answer both before anyone asks. Write your pod’s mission and margin statement: what the project preserves or strengthens, what it costs and where the money comes from, what it saves, earns, or protects, and where it sits on the matrix. Reallocating an existing budget counts. A past pod funded its idea from the event budgets departments already had.',
  'focus/1': 'Lesson four, your brief. Your pod submits one brief, no longer than three pages, due Friday, November twentieth. It has seven parts. This week you draft the first three: the focus area, the challenge and why it matters strategically, and the connection to Vanderbilt’s priorities. Next week, Course Two covers the rest. Three winners will be named, one per focus area, so choose on purpose. Practice the call with five challenges. Plenty of ideas touch more than one area; pick the one where your solution does the most work.',
  'draft/1': 'Draft the first page of your brief. Choose your focus area. Write the challenge in one sentence: who is affected, and what happens today. Say why it matters strategically: what it costs to wait, in mission, money, people, or reputation. And connect it to Vanderbilt’s priorities by name. Your opening story and your mission and margin statement fold into the draft automatically. Copy it into your pod’s shared document before you meet.',
  'quiz/1': 'A quick check. Five questions, one at a time, with feedback after each. Four of five finishes the check, and you can retake it anytime.',
  'nextstep/1': 'Your four moves for the week. Meet your pod for about forty five minutes and agree on one challenge and one focus area. Put your draft and your storyline in the pod’s shared document. Post in your cohort’s Teams channel on this week’s topic, and reply to at least one colleague. A starter post is ready to copy, built from what you wrote. There is also a pod meeting agenda you can copy, and you can print your takeaway. Tap each move to commit.',
  'learn/1': 'That is Course One. Take it to your pod. Course Two opens the week of November ninth, with entrepreneurial mindset, reputational stewardship, and high-performing teams, and it drafts the rest of your brief. Crescere aude. Dare to grow.'
};
