/* ══════════ LEADERSHIP REDEFINED · COURSE TWO · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus short clips
   for stops, cards, principles, and situations. Every page script follows the
   same adult learning arc (Knowles; Mayer):
     1. Breadcrumb back: where you are and how it connects to the last page.
     2. Why it matters to you: the problem it helps you solve this month.
     3. Teach: the idea in plain words, with one concrete example.
     4. Your experience: a prompt to connect it to your own work.
     5. Do: what to do on this page, and what you will get from it.
     6. Breadcrumb forward: what comes next.
   Played from ../assets/audio/course-two/<key with / as ->.mp3; the browser's
   voice reads the same words if a clip is missing. Diermeier is written
   Deer-myer for the voice; the screen keeps the real spelling.
   No em or en dashes. */
window.LR_NARR = {
  /* ── WELCOME ── */
  'home/1': 'Welcome to Course Two of Leadership Redefined. Last week, in Course One, your pod made the case: a focus area, a challenge, and why it matters to Vanderbilt. This week you design what you will actually do about it, and the team that will do it. That is the second half of your brief: the solution, the plan, the metrics, and how it lasts. Three topics carry you there. Entrepreneurial mindset, so your solution starts small and learns fast. Reputational stewardship, so it protects the trust it depends on. And high-performing teams, so the people delivering it, starting with your own pod, do their best work. As before, each page has one idea and one thing to do, and you bring the experience. Every activity asks you to apply the idea to your own work or your pod’s idea. It takes about an hour. Plan to finish by Friday, November thirteenth, so your pod has a complete first draft before the final week. Tap Start Course Two when you are ready.',

  /* ── LESSON 1 · ENTREPRENEURIAL MINDSET ── */
  'route/1': 'Here is your map for the week. Lesson one is the entrepreneurial mindset, taught through a real Vanderbilt turnaround, and it ends with your pod’s first pilot. Lesson two is reputational stewardship: how trust is earned and kept, and what your project means for Vanderbilt’s name. Lesson three is high-performing teams, with Vice Chancellor Candice Storey Lee, and a health check on your own pod. Lesson four is your brief: strong metrics and a draft of sections four to seven. Each lesson closes with a short wrap-up where you explain the ideas back in your own words. Tap each stop to preview it, then turn the page to start with the Chancellor.',
  'route/g1': 'Stop one, entrepreneurial mindset. The Chancellor introduces it, then you study how Vanderbilt’s fundraising team went from flat to record-breaking, and you turn your pod’s challenge into a pilot.',
  'route/g2': 'Stop two, reputational stewardship. The Chancellor again, the trust radar, where reputation is made, when to act, three calls under pressure, and your project’s reputational statement.',
  'route/g3': 'Stop three, high-performing teams. The Chancellor introduces the topic, then Candice Storey Lee’s six principles, three leadership calls, and a health check on your pod.',
  'route/g4': 'Stop four, your brief. Sort strong and weak metrics, draft sections four to seven, and check what you can now apply.',

  'swot/1': 'Start with the Chancellor’s short video on the entrepreneurial mindset. Then let us define it, because the phrase gets used loosely. An entrepreneurial mindset means acting like a founder inside an institution. You spot a problem or an opening, diagnose it honestly, act before everything is certain, test small, learn fast, and scale what works, using the resources you can actually reach. It is how a large university moves at the uncommon speed, agility, and scale you met in Course One. Vice Chancellor John Lutz taught this topic to the program through a case: the transformation of Vanderbilt’s fundraising. And the first lesson of that case is where it began. Not with a solution. With a diagnosis. His team laid out strengths, weaknesses, opportunities, and threats with real candor. Look closely at the weaknesses: three of the four were about people and culture, not tools. Think about a problem in your own area. Have you diagnosed it, or jumped to a fix? Tap each quadrant. Next, the numbers that came out of it.',
  'swot/f1': 'Strengths. A strong brand, pockets of talented people, and support from the Chancellor and the Board of Trust. The raw material was there; it needed connecting.',
  'swot/f2': 'Weaknesses. Silos, a rigid culture, a hostile environment, and out-of-date processes and systems. Three of the four are about people, which told the team where the fix had to start.',
  'swot/f3': 'Opportunities. New leadership, an investment mentality, and willing fellow travelers. Change needs allies, so find the people who already want it.',
  'swot/f4': 'Threats. Time was short, the pressure was real, and the environment was fragile. Move fast enough to show results, and carefully enough not to break what works.',

  'numbers/1': 'You saw the diagnosis. Now the result. Lutz opened his story with the ending, and so will we, but you guess first. Making a guess before the reveal, even a wrong one, makes the answer far easier to remember. From nineteen ninety eight to twenty nineteen, new commitments stayed roughly flat. Then the team acted on its diagnosis. After you guess all four tiles, read the card below them. It holds the entrepreneurial point. Over twenty twenty to twenty twenty five, on three-year averages, money raised more than doubled, while the investment in fundraising rose by about half. In other words, they invested where the diagnosis pointed, and measured the return. Ask yourself: where in your own area would a modest, targeted investment produce an outsized result? Next, exactly what they changed.',

  'moves/1': 'You have seen the before and after. Now the how, which is the part you can reuse. Lutz says successful change leadership needs ambidexterity: alternating between assessment and action, rather than doing only one. He named five moves. Listen carefully to the key people, which also buys time with critics. Make clear-eyed assessments, against the best, not the average. Deal with resistance and underperformance, while giving hope to the leaders coming up. Drive people, process, and technology agendas at the same time. And look beyond best practices, even outside higher education. Then every tactic got a home in one of four categories: people and culture, collaboration and engagement, motivation and incentives, and process and systems. Each had an owner and a date. Notice that your brief asks for the same thing: a solution across people, process, and technology, with owners and a timeline. Think about the last change you led. Did it touch all three, or only one? Sort six real tactics, and read why after each. Next, how to tell what kind of problem you are facing.',

  'kind/1': 'You have seen how one leader drove change. But the right approach depends on the kind of problem in front of you, and choosing wrong is one of the most common leadership mistakes. The program’s pre-work, A Leader’s Framework for Decision Making, names four kinds. Simple problems have a known best practice: sense, categorize, respond. Complicated problems have a right answer that experts can find: sense, analyze, respond. Complex problems have no right answer up front; cause and effect show up only in hindsight. There you probe with small, safe experiments, sense what happens, and grow what works. And chaotic situations need action first, to restore order. The classic mistake is treating a complex problem as merely complicated, and spending months analyzing what only a pilot can reveal. Most capstone challenges are complex, because they involve people’s behavior. Think of a recent problem at work. Which kind was it, and did you treat it that way? Sort four situations. Next, you turn your pod’s challenge into a pilot.',

  'reframe/1': 'You know your pod’s challenge is probably complex. So the next step is not a big rollout. It is a reframe and a pilot. Here is a five-step method. Name the assumption everyone makes about the problem. Flip it with a what if; many new ideas start as a reversed assumption. Borrow an idea from outside higher education, from a hotel, a hospital, a retailer, or a bank. Shrink it to a pilot small enough to start without new approvals. And set a scale rule before you start, so the results decide, not opinions. One past pod did exactly this. The assumption was that students attend career programs if the programs are good. The reframe: what if attending put real money into a student’s own investment account? Think about an assumption in your own area that nobody questions anymore. That is often where the best reframe hides. Open the full example if you want to see it worked through. Then capture your pod’s reframe and pilot. It is this week’s team artifact, and it folds into your brief draft. Next, a wrap-up for lesson one.',

  'recap1/1': 'That is lesson one. Three ideas. Diagnose before you build: the turnaround began with an honest benchmark and root causes, and three of four weaknesses were about people. Change three things at once: people, process, and technology together, with every tactic owned and dated. And probe complex problems: when no one knows the answer, run a small pilot, learn, and scale what works. Now apply it. Write which kind of problem your pod’s challenge is, and the smallest pilot that would teach you the most. Explaining it in your own words, about your own project, is what makes it stick. Next, lesson two: protecting the trust your idea depends on.',

  /* ── LESSON 2 · REPUTATIONAL STEWARDSHIP ── */
  'trust/1': 'Welcome to lesson two. In lesson one you designed a bold pilot. Every bold idea borrows against something fragile: Vanderbilt’s reputation. Start with the Chancellor’s video. Then remember the loop from Course One: reputation brings talent and funding, and those build more reputation. The loop can also run in reverse. That is why leaders treat reputation as infrastructure: a system built every day by service, operations, and decisions, not a campaign. In his book Reputation Rules, the program’s pre-work, Chancellor Deer-myer argues that when something goes wrong, people judge an institution less on the facts than on whether they trust it. He draws trust as a radar with four axes: transparency, expertise, commitment, and empathy. Strong on all four, the shape is a full diamond. A crisis finds the dent. Two more of his tools are worth knowing by name. Credibility transfer means a trusted third party, such as an outside expert or a partner, lends you their credibility. Room to maneuver means trust built before a crisis buys time and options during it. His team has used these tools in real Vanderbilt moments, from campus protests to public scrutiny of clinical care. Think of an organization you stopped trusting. Which axis of the radar did it dent? Tap each driver. Next, where reputation is actually made.',
  'terrain/1': 'You have the trust radar. Now, where is reputation made? Not mainly in what Vanderbilt says. The university speaks to its audiences directly, but most of what they hear arrives through the media. And around the media sits a second circle: activists and advocates who shape what the media and your constituents pay attention to. The Chancellor maps coverage on two axes. Up is how important an issue is to society. Across is how interested a mass audience is. Low on both is simple reporting, the wire brief. Important but niche is in-depth coverage, which runs on experts and data. Popular but light is extensive reporting, cable infotainment. High on both is mass-market coverage, which runs on testimony and drama. Here is the key lesson: stories migrate. The Chancellor gave two examples. A routine sports story became a story about the rise of antisemitism after a post about Kanye West. And clinical care guidelines became a harming children story through a social media campaign and political controversy about transgender issues. When a story moves up and to the right, data stops being enough, and a human voice and empathy matter most. Think of a story about your area. Where on the map does it sit today, and what could move it? Now place six stories, and read what each corner asks of you. Next, timing: when to act.',
  'timing/1': 'You know where a story sits. Now the hardest question in reputation: when do you act? The Chancellor draws two lines over time. Control starts high and falls. Stakes start low and then rise sharply. The optimal time to act is at the start, when control is high and the stakes are low. The typical time to act is later, when the lines cross and the stakes spike. By then, the story is no longer yours. So he frames reputation work as a cycle in three parts. Before: prevention, fixing what could go wrong, and preparation, deciding who speaks, what you would say, and who you would call. During: identification, spotting it early; containment, stopping the spread and telling the people affected; and solution, fixing the cause with an owner and a date. After: learning, which feeds the next round of prevention and preparation. Always learning. Here is a small example. A complaint about a confusing form gets ten replies online on Monday. Fixing the form that afternoon is the optimal time. Waiting for a reporter to call on Thursday is the typical time. Think of the last small problem in your area that grew. When did someone first notice it? Now sort six actions into before, during, or after. Next, three calls under pressure.',
  'trust/f1': 'Transparency. Be open about what happened and what you are doing about it. Silence reads as hiding.',
  'trust/f2': 'Expertise. Show you know how to fix the problem. Bring the facts and the plan, not only the apology.',
  'trust/f3': 'Commitment. Show the issue matters to you. Name an owner and a date, and report back when you said you would.',
  'trust/f4': 'Empathy. Show you understand how the people affected feel. Start with them before you start with the process.',

  'pressure/1': 'You have the radar, the terrain, and the timing. Now use them under pressure, where they matter most. Reputation is not only the press office’s job; staff leaders make most of the calls that build or drain it. When something goes wrong, five moves help. Move fast, because the first account of a story tends to stick. Tell the truth, including what you do not know yet. Show the plan and the owner, then report back. Start with the people affected, before the process. And bring in the offices that own the issue, such as Communications or General Counsel, so Vanderbilt speaks with one voice. Think of a moment when something went wrong in your area and word got out. What did people remember about how it was handled? Here are three situations. Choose what you would do, then try the other answers to see what they would cost. That comparison is where most of the learning happens. Next, you write your project’s reputational statement.',
  'pressure/s1': 'Situation one. Your office emailed admitted students the wrong deadline, and a parent’s post about it is spreading. What do you do first?',
  'pressure/s2': 'Situation two. A speaker invited by a group your unit supports has upset many people, and you are getting calls to cancel. What do you do?',
  'pressure/s3': 'Situation three. A sponsor offers generous money if the Vanderbilt name appears in its consumer ads. What do you do?',

  'repstatement/1': 'You have practiced protecting trust. Now apply it to your pod’s idea, because judges will ask how it affects Vanderbilt’s name. A reputational statement says, in one or two sentences, why the project makes Vanderbilt more credible, meaning we do what we say, and more visible, meaning the right people notice. Just as important is the risk scan. Name the upside: who will notice, and what will they say? Name the top two risks: what could go wrong in public? And say how you would protect trust if one happened, using the four drivers. Judges trust a pod that names its own risks. Ask yourself: what is the headline nobody on your pod wants to read about this idea? One past pod built its whole idea around this: a secure internal assistant that gives staff approved talking points when a reputational issue comes up. Open the strong example if it helps, then draft your pod’s version. Next, a wrap-up for lesson two.',

  'recap2/1': 'That is lesson two. Three ideas. Reputation is infrastructure: it turns visibility into talent, funding, partners, and access, and it is built every day. Trust has four drivers: transparency, expertise, commitment, and empathy, and a crisis finds the dent in the radar. And timing matters: act early, while you still have control, because stories migrate toward the loud corner of the terrain. And every leader is a steward: move fast, tell the truth, show the plan, start with the people affected, and bring in the right offices. Now apply it. Name one reputational risk in your pod’s idea, and which driver of trust you would lean on if it happened. Next, lesson three: the teams that deliver.',

  /* ── LESSON 3 · HIGH-PERFORMING TEAMS ── */
  'lee/1': 'Welcome to lesson three. Your pilot and your reputational plan only work if a team delivers them, starting with your own pod. Begin with the Chancellor’s introduction. Then meet Candice Storey Lee, Vice Chancellor for Athletics and University Affairs and Athletic Director. She came to Vanderbilt as a student-athlete, captained the women’s basketball team, and earned three Vanderbilt degrees. She rose from an internship to lead the department in twenty twenty, in the middle of a pandemic, the first Black woman to lead an athletics department in the SEC. Under her leadership, Vanderbilt beat the number one team in the country in twenty twenty four, won its first ten-game football season in twenty twenty five, and earned the top seed in college baseball. Think about the best team you have ever been part of. What made it work? Hold that answer; you will see much of it in her approach. Her core idea fits any team on campus: you can’t always control for winning, but you can always control your ability to compete. Try four fact or fiction statements. Next, the six principles behind her teams.',

  'principles/1': 'You have met the leader. Now the ideas she returns to, which you can use with any team. These six principles are a summary of her public interviews and statements, each paired with research on teams. Control the controllables: leaders build the conditions, and the team brings the effort. Lead with values, and keep the joy: winning is a result, not the reason. Hire for character, then back people through a hard start. Hold high standards with real support: growth and accountability together. Celebrate, then stay hungry. And prepare early, and build together. As you tap each one, ask yourself a direct question: which of these does my own team already do well, and which is missing? You will choose one to try in the wrap-up. Next, a closer look at standards and safety.',
  'principles/f1': 'Control the controllables. In her words, it is easy to lament things you can’t control, and we never want to do that. Researcher J. Richard Hackman found the same: leaders shape performance most through the conditions they create.',
  'principles/f2': 'Lead with values, and keep the joy. Winning is a result, but it is not the thing that brings you joy. Google’s research on teams found people do better work when it has meaning and impact.',
  'principles/f3': 'Hire for character, then back people. She hired football coach Clark Lea for his integrity and strategic thinking, and kept backing him through a two and ten first season. Three seasons later came the upset of number one Alabama.',
  'principles/f4': 'High standards, real support. When a star player crossed a line in public, she called it unacceptable, and in the same statement promised continued support as he learned. Growth and accountability.',
  'principles/f5': 'Celebrate, then stay hungry. After beating number one Alabama, she called it just the beginning, for all seventeen sports and for the university. Proud, but not satisfied.',
  'principles/f6': 'Prepare early, and build together. Her department prepared for revenue sharing in college sports about a year and a half before it arrived. As she said when she took the job, anything is possible if we all work together.',

  'teamcalls/1': 'You just saw growth and accountability as one of Lee’s principles. Research gives it a name. Amy Edmondson of Harvard shows that teams work in one of four zones, depending on two things: the standards they hold, and their psychological safety, meaning the shared belief that it is safe to speak up, ask, and admit mistakes. Low on both is apathy. Safety without standards is comfort. Standards without safety is anxiety, where people work hard and hide problems until it is too late. High on both is the learning zone, where high-performing teams live. Leaders build safety on purpose. Frame the work as learning. Admit your own limits. Ask real questions, and invite the quietest person first. And respond well to bad news, because how you react the first time decides whether you hear the second. Think about your own team. Which zone is it in on a hard week? Now three moments drawn from Vanderbilt athletics. Make your call, then try the others. Next, a check on your own pod.',
  'teamcalls/s1': 'Situation one. Your team just had its biggest win ever, and it is Monday morning. What do you do?',
  'teamcalls/s2': 'Situation two. Your best performer crossed a line in public. What do you do?',
  'teamcalls/s3': 'Situation three. A leader you hired has had a rough first year. What do you do?',

  'health/1': 'You have the principles and the learning zone. Now turn them on a real team: your pod. It is a team with a deadline, which makes it a good place to practice. Google studied more than one hundred eighty of its own teams in a project called Aristotle, and found that how a team works matters more than who is on it. Five dynamics stood out. Psychological safety: it is safe to take risks with each other. Dependability: people deliver quality work on time. Structure and clarity: clear goals, roles, and plans. Meaning: the work matters to each person. And impact: people believe the work makes a difference. Safety mattered most. Think about your pod\u2019s last meeting. Did everyone speak? Rate your pod honestly on each one. The read shows your strongest dynamic and the one to work on next, with a specific action. Then ask each pod member to take it and compare in your next meeting. Next, a wrap-up for lesson three.',

  'recap3/1': 'That is lesson three. Three ideas. Control the controllables: leaders build the conditions, and the team brings the effort. Aim for the learning zone: high standards plus psychological safety, which leaders build on purpose through how they frame work and respond to bad news. And how a team works matters more than who is on it: safety, dependability, clarity, meaning, and impact. Now commit to something specific. Choose one of Candice Storey Lee’s principles to try with your own team next week, and write what you will actually do. Next, lesson four: finishing the brief.',

  /* ── LESSON 4 · YOUR BRIEF ── */
  'metrics/1': 'Welcome to lesson four. You have a pilot, a reputational plan, and a team. Now the second half of your brief: sections four to seven. Start with metrics, because this is where many briefs go soft, and judges notice. A strong metric has four parts. A baseline: where things are today. A target: the number you are aiming for. A date: when you will check. And it measures an outcome, not an output. Outcomes are what change for people, like days saved or students coming back. Outputs are what you produced, like emails sent or a website launched. Outputs belong in your timeline; outcomes belong in your metrics. Ask yourself the question in the headline: would you know in ninety days whether it worked? Sort six metrics, strong or weak. Next, you draft the plan.',

  'draft/1': 'You know what a strong metric looks like. Now draft sections four to seven, and notice how much you already have. Your pilot and your reputation scan fold into this draft automatically. Section four is the integrated solution: what changes for people, for process, and for technology, together, just as in Lutz’s turnaround. Section five is implementation: each step with an owner role and a date, starting with your pilot. Section six is two or three strong metrics. Section seven is sustainability: who owns it after your pod disbands, how the second year is funded, and how it becomes normal work. Ask yourself the question every sponsor asks: if your pod disappeared tomorrow, who would keep this running? Open the strong example to see all four sections worked through, and read the checklist before you submit. Copy your draft into your pod’s shared document before you meet. Next, eight situations to check what you can apply.',

  'quiz/1': 'You have learned the ideas and used them on your own project. Now check whether you can apply them to situations you have not seen. Eight short scenarios, drawn from all three topics and your brief. Choose what you would do, then read the explanation, which names the idea behind the best answer. Six of eight completes the check, and you can retake it anytime. Next, your moves for the week.',

  'nextstep/1': 'You are nearly done with Course Two. This page turns the course into four moves for the week. Meet your pod for about an hour: merge your drafts, compare health checks, and set owners and dates for the final week. Finish a full first draft, all seven sections in about three pages, by Friday, November thirteenth. Post in your Teams channel and reply to a colleague; a starter post is ready to copy, built from what you wrote. Tap each move to commit. Copy the pod meeting agenda if it helps, and print this week’s takeaway, which collects your overview, your answers, and your drafts in one place. Next, a short close.',

  'learn/1': 'That is Course Two. Your pod now has both halves of its brief: the case from Course One, and the plan from this week, with a pilot, a reputational strategy, strong metrics, and a team ready to deliver. Week four, the week of November sixteenth, is for polishing. Your brief is due Friday, November twentieth, and three winners will be named, one in each focus area. Crescere aude. Dare to grow.'
};
