/* ══════════ LEADERSHIP REDEFINED · COURSE TWO · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus short clips
   for stops, cards, principles, and situations. Every page script follows the
   same adult learning arc (Knowles; Mayer):
     1. Breadcrumb back: where you are and how it connects to the last page.
     2. Why it matters to you: the problem it helps you solve this month.
     3. Teach: the idea in plain words, with one concrete example.
     4. Your experience: a prompt to connect it to your own work.
     5. Do: what to do on this page, and what you will get from it.
     6. Breadcrumb forward: what comes next.
   Played from ../assets/audio/course-two/<key with / as ->.mp3; the browser's
   voice reads the same words if a clip is missing. Diermeier is written
   Deer-myer for the voice; the screen keeps the real spelling.
   No em or en dashes. */
window.LR_NARR = {
  /* ── WELCOME ── */
  'home/1': 'Welcome to Course Two of Leadership Redefined. Last week, in Course One, your pod made the case: a focus area, a challenge, and why it matters to Vanderbilt. This week you design what you will actually do about it, and the team that will do it. That is the second half of your brief: the solution, the plan, the metrics, and how it lasts. Three topics carry you there. Entrepreneurial mindset, so your solution starts small and learns fast. Reputational stewardship, so it protects the trust it depends on. And high-performing teams, so the people delivering it, starting with your own pod, do their best work. As before, each page has one idea and one thing to do, and you bring the experience. Every activity asks you to apply the idea to your own work or your pod’s idea. It takes about an hour. Plan to finish by Friday, November thirteenth, so your pod has a complete first draft before the final week. Tap Start Course Two when you are ready.',

  /* ── LESSON 1 · ENTREPRENEURIAL MINDSET ── */
  'route/1': 'Here is your map for the week. Module four is the entrepreneurial mindset, taught through a real Vanderbilt turnaround, and it ends with your pod’s first pilot. Module five is reputational stewardship: how trust is earned and kept, and what your project means for Vanderbilt’s name. Module six is high-performing teams, with Vice Chancellor Candice Storey Lee, and a health check on your own pod. The last part is your brief: strong metrics and a draft of sections four to seven. Each lesson closes with a short wrap-up where you explain the ideas back in your own words. Tap each stop to preview it, then turn the page to start with the Chancellor.',
  'route/g1': 'Stop one, entrepreneurial mindset. The Chancellor introduces it, then you study how Vanderbilt’s fundraising team went from flat to record-breaking, how radical collaboration made it work, and you turn your pod’s challenge into a pilot.',
  'route/g2': 'Stop two, reputational stewardship. The Chancellor again, the trust radar, where reputation is made, when to act, three calls under pressure, and your project’s reputational statement.',
  'route/g3': 'Stop three, high-performing teams. The Chancellor introduces the topic, then Candice Storey Lee’s six principles in her own words, and an optional go deeper on the research behind great teams.',
  'route/g4': 'Stop four, your brief. Sort strong and weak metrics, draft sections four to seven, and check what you can now apply.',

  'swot/1': 'Start with the Chancellor’s short video on the entrepreneurial mindset. Then let us define it, because the phrase gets used loosely. An entrepreneurial mindset means acting like a founder inside an institution. You spot a problem or an opening, diagnose it honestly, act before everything is certain, test small, learn fast, and scale what works, using the resources you can actually reach. It is how a large university moves at the uncommon speed, agility, and scale you met in Course One. Vice Chancellor John Lutz taught this topic to the program through a case: the transformation of Vanderbilt’s fundraising. And the first lesson of that case is where it began. Not with a solution. With a diagnosis. His team laid out strengths, weaknesses, opportunities, and threats with real candor. Look closely at the weaknesses: three of the four were about people and culture, not tools. Think about a problem in your own area. Have you diagnosed it, or jumped to a fix? Tap each quadrant. Next, the numbers that came out of it.',
  'swot/f1': 'Strengths. A strong brand, pockets of talented people, and support from the Chancellor and the Board of Trust. The raw material was there; it needed connecting.',
  'swot/f2': 'Weaknesses. Silos, a rigid culture, a hostile environment, and out-of-date processes and systems. Three of the four are about people, which told the team where the fix had to start.',
  'swot/f3': 'Opportunities. New leadership, an investment mentality, and willing fellow travelers. Change needs allies, so find the people who already want it.',
  'swot/f4': 'Threats. Time was short, the pressure was real, and the environment was fragile. Move fast enough to show results, and carefully enough not to break what works.',

  'numbers/1': 'You saw the diagnosis. Now the result. Lutz opened his story with the ending, and so will we, but you guess first. Making a guess before the reveal, even a wrong one, makes the answer far easier to remember. From nineteen ninety eight to twenty nineteen, new commitments stayed roughly flat. Then the team acted on its diagnosis. After you guess all four tiles, read the card below them. It holds the entrepreneurial point. Over twenty twenty to twenty twenty five, on three-year averages, money raised more than doubled, while the investment in fundraising rose by about half. In other words, they invested where the diagnosis pointed, and measured the return. Ask yourself: where in your own area would a modest, targeted investment produce an outsized result? Next, exactly what they changed.',

  'moves/1': 'You have seen the before and after. Now the how, which is the part you can reuse. Lutz says successful change leadership needs ambidexterity: alternating between assessment and action, rather than doing only one. He named five moves. Listen carefully to the key people, which also buys time with critics. Make clear-eyed assessments, against the best, not the average. Deal with resistance and underperformance, while giving hope to the leaders coming up. Drive people, process, and technology agendas at the same time. And look beyond best practices, even outside higher education. Then every tactic got a home in one of four categories: people and culture, collaboration and engagement, motivation and incentives, and process and systems. Each had an owner and a date. Notice that your brief asks for the same thing: a solution across people, process, and technology, with owners and a timeline. Think about the last change you led. Did it touch all three, or only one? Sort six real tactics, and read why after each. Next, the principle underneath all of them: radical collaboration.',

  'collab/1': 'You just sorted the change moves. Underneath all of them was one principle. Lutz said the Chancellor’s call for Radical Collaboration underpinned every change initiative. It has three parts. First, start from the people you serve. Gift proposals reflected donor interests, aligned with the mission, and the team worked with donors rather than trying to steer them. Second, it is a team sport. Many roles are needed to execute a strategy, and every Vanderbilt leader is a fundraiser. Third, operate as One Vanderbilt. Donors who support several areas give the most, so every key prospect had a cross-Vanderbilt strategy, backed by shared credit, so two schools could win the same gift instead of competing for it. Lutz also led the people around the change, not only the work. He bought time with potential critics by listening. He sent serious signals that he meant business. He worked to reverse an image as a poor partner. He built trust and loyalty with top producers. And he used early wins to build momentum. Think about your pod’s idea. Which office could block it, and which could make it twice as strong if it shared the credit? Now map the people around your idea. It saves here and prints in your takeaway. Next, you turn your pod’s challenge into a pilot.',
  'kind/1': 'This page is an optional go deeper. Module four followed Vice Chancellor Lutz from assessment to action, and the Chancellor’s levers end with pilot, learn, and scale. Here is a framework that explains when piloting beats planning. This idea is new to the program. A Harvard Business Review article by David Snowden and Mary Boone, A Leader’s Framework for Decision Making, names four kinds of problems. Simple problems have a known best practice. Complicated problems have a right answer that experts can find. Complex problems have no right answer up front; cause and effect show up only in hindsight, so you probe with small, safe experiments and grow what works. And chaotic situations need action first, to restore order. The classic mistake is treating a complex problem as merely complicated, and spending months analyzing what only a pilot can reveal. Think of a recent problem at work. Which kind was it? Sort four situations if you want the practice, and use the links to read the article and research on ambidextrous organizations. Next, module five: reputational stewardship.',

  'reframe/1': 'Lutz’s turnaround moved back and forth between assessment and action, and the Chancellor’s own levers end with pilot, learn, and scale. So the next step for your pod is not a big rollout. It is a reframe and a pilot. Here is a five-step method. Name the assumption everyone makes about the problem. Flip it with a what if; many new ideas start as a reversed assumption. Borrow an idea from outside higher education, from a hotel, a hospital, a retailer, or a bank. Shrink it to a pilot small enough to start without new approvals. And set a scale rule before you start, so the results decide, not opinions. One past pod did exactly this. The assumption was that students attend career programs if the programs are good. The reframe: what if attending put real money into a student’s own investment account? Think about an assumption in your own area that nobody questions anymore. That is often where the best reframe hides. Open the full example if you want to see it worked through. Then capture your pod’s reframe and pilot. It is this week’s team artifact, and it folds into your brief draft. Next, what module four means for you: for your capstone, and as a manager.',

  'me1/1': 'Module four was the entrepreneurial mindset. Here is what it means for you. For your capstone: diagnose before you solve, and notice how many root causes are about people. Design the smallest pilot that would prove your idea, with a scale rule set before you start. And map the people: partners who share the credit, a likely critic, your top producers, and the early win. As a manager: alternate assessment and action, listening and benchmarking, then moving, then looking again. Change people, process, and technology together, because fixing one alone rarely sticks. And run small experiments on complex problems, then celebrate the early wins out loud. Think about a problem your team keeps analyzing. Could a small test answer it faster? Write the one thing you will try in the next two weeks. Next, a short wrap-up for module four.',
  'recap1/1': 'That is module four. Three ideas. Diagnose before you build: the turnaround began with an honest benchmark and root causes, and three of four weaknesses were about people. Change three things at once: people, process, and technology together, with every tactic owned and dated. And win together: radical collaboration means starting from the people you serve, treating the work as a team sport, and sharing the credit as One Vanderbilt. Now apply it. Write the smallest pilot that would prove your pod’s idea, and who must share the credit for it. Explaining it in your own words, about your own project, is what makes it stick. Next, an optional go deeper on the kinds of problems leaders face, or go straight on to module five: protecting the trust your idea depends on.',

  /* ── LESSON 2 · REPUTATIONAL STEWARDSHIP ── */
  'trust/1': 'Welcome to module five. In module four you designed a bold pilot. Every bold idea borrows against something fragile: Vanderbilt’s reputation. Start with the Chancellor’s video. Then remember the loop from Course One: reputation brings talent and funding, and those build more reputation. The loop can also run in reverse. That is why leaders treat reputation as infrastructure: a system built every day by service, operations, and decisions, not a campaign. In his book Reputation Rules, Chancellor Daniel Deer-myer argues that when something goes wrong, people judge an institution less on the facts than on whether they trust it. He draws trust as a radar with four axes: transparency, expertise, commitment, and empathy. Strong on all four, the shape is a full diamond. A crisis finds the dent. Two more of his tools are worth knowing by name. Credibility transfer means a trusted third party, such as an outside expert or a partner, lends you their credibility. Room to maneuver means trust built before a crisis buys time and options during it. His team has used these tools in real Vanderbilt moments, from campus protests to public scrutiny of clinical care. Think of an organization you stopped trusting. Which axis of the radar did it dent? Tap each driver. Next, where reputation is actually made.',
  'terrain/1': 'You have the trust radar. Now, where is reputation made? Not mainly in what Vanderbilt says. The university speaks to its audiences directly, but most of what they hear arrives through the media. And around the media sits a second circle: activists and advocates who shape what the media and your constituents pay attention to. The Chancellor maps coverage on two axes. Up is how important an issue is to society. Across is how interested a mass audience is. Low on both is simple reporting, the wire brief. Important but niche is in-depth coverage, which runs on experts and data. Popular but light is extensive reporting, cable infotainment. High on both is mass-market coverage, which runs on testimony and drama. Here is the key lesson: stories migrate. The Chancellor gave two examples. A routine sports story became a story about the rise of antisemitism after a post about Kanye West. And clinical care guidelines became a harming children story through a social media campaign and political controversy about transgender issues. When a story moves up and to the right, data stops being enough, and a human voice and empathy matter most. Think of a story about your area. Where on the map does it sit today, and what could move it? Now place six stories, and read what each corner asks of you. Next, timing: when to act.',
  'timing/1': 'You know where a story sits. Now the hardest question in reputation: when do you act? The Chancellor draws two lines over time. Control starts high and falls. Stakes start low and then rise sharply. The optimal time to act is at the start, when control is high and the stakes are low. The typical time to act is later, when the lines cross and the stakes spike. By then, the story is no longer yours. So he frames reputation work as a cycle in three parts. Before: prevention, fixing what could go wrong, and preparation, deciding who speaks, what you would say, and who you would call. During: identification, spotting it early; containment, stopping the spread and telling the people affected; and solution, fixing the cause with an owner and a date. After: learning, which feeds the next round of prevention and preparation. Always learning. Here is a small example. A complaint about a confusing form gets ten replies online on Monday. Fixing the form that afternoon is the optimal time. Waiting for a reporter to call on Thursday is the typical time. Think of the last small problem in your area that grew. When did someone first notice it? Now sort six actions into before, during, or after. Next, three calls under pressure.',
  'trust/f1': 'Transparency. Be open about what happened and what you are doing about it. Silence reads as hiding.',
  'trust/f2': 'Expertise. Show you know how to fix the problem. Bring the facts and the plan, not only the apology.',
  'trust/f3': 'Commitment. Show the issue matters to you. Name an owner and a date, and report back when you said you would.',
  'trust/f4': 'Empathy. Show you understand how the people affected feel. Start with them before you start with the process.',

  'pressure/1': 'You have the radar, the terrain, and the timing. Now use them under pressure, where they matter most. Reputation is not only Marketing and Communications’ job; staff leaders make most of the calls that build or drain it. When something goes wrong, five moves help. Move fast, because the first account of a story tends to stick. Tell the truth, including what you do not know yet. Show the plan and the owner, then report back. Start with the people affected, before the process. And bring in the offices that own the issue, such as Marketing and Communications or General Counsel, so Vanderbilt speaks with one voice. Think of a moment when something went wrong in your area and word got out. What did people remember about how it was handled? Here are three situations. Choose what you would do, then try the other answers to see what they would cost. That comparison is where most of the learning happens. Next, you write your project’s reputational statement.',
  'pressure/s1': 'Situation one. Your office emailed admitted students the wrong deadline, and a parent’s post about it is spreading. What do you do first?',
  'pressure/s2': 'Situation two. A speaker invited by a group your unit supports has upset many people, and you are getting calls to cancel. What do you do?',
  'pressure/s3': 'Situation three. A sponsor offers generous money if the Vanderbilt name appears in its consumer ads. What do you do?',

  'repstatement/1': 'You have practiced protecting trust. Now apply it to your pod’s idea, because judges will ask how it affects Vanderbilt’s name. A reputational statement says, in one or two sentences, why the project makes Vanderbilt more credible, meaning we do what we say, and more visible, meaning the right people notice. Just as important is the risk scan. Name the upside: who will notice, and what will they say? Name the top two risks: what could go wrong in public? And say how you would protect trust if one happened, using the four drivers. Judges trust a pod that names its own risks. Ask yourself: what is the headline nobody on your pod wants to read about this idea? One past pod built its whole idea around this: a secure internal assistant that gives staff approved talking points when a reputational issue comes up. Open the strong example if it helps, then draft your pod’s version. Next, what module five means for you: for your capstone, and as a manager.',

  'me2/1': 'Module five was reputational stewardship. Here is what it means for you. For your capstone: write your reputational statement, the upside, who notices, and your top two risks. Check your idea on the trust radar. And plan prevention and preparation: who speaks, and which offices you would call. As a manager: build an early-warning habit, and reward the person who raises a small problem early, while you still have control. When something goes wrong, start with the people affected, tell the truth, show the plan, and report back. And know your partners in Marketing and Communications and General Counsel before you need them. Think about the last small problem on your team that grew. Who saw it first? Write the one thing you will try in the next two weeks. Next, a short wrap-up for module five.',
  'recap2/1': 'That is module five. Three ideas. Reputation is infrastructure: it turns visibility into talent, funding, partners, and access, and it is built every day. Trust has four drivers: transparency, expertise, commitment, and empathy, and a crisis finds the dent in the radar. And timing matters: act early, while you still have control, because stories migrate toward the loud corner of the terrain. And every leader is a steward: move fast, tell the truth, show the plan, start with the people affected, and bring in the right offices. Now apply it. Name one reputational risk in your pod’s idea, and which driver of trust you would lean on if it happened. Next, an optional go deeper on the Chancellor’s book Reputation Rules, or go straight on to module six: the teams that deliver.',

  /* ── LESSON 3 · HIGH-PERFORMING TEAMS ── */
  'gdrep/1': 'This page is an optional go deeper. Module five gave you the frameworks Chancellor Daniel Deer-myer shared at the Symposium: the trust radar, the terrain, and when to act. His book Reputation Rules, new to this program, shows those ideas at work in real crises, from Mercedes and Toyota to Shell and Walmart, and explains credibility transfer and room to maneuver step by step. A Harvard Business Review article, Reputation and Its Risks, adds a manager’s view: reputation risk deserves the same discipline as financial risk. Why it matters here: the more you see these frameworks in real cases, the faster you will spot the next issue while you still have control. Think about an organization whose crisis you followed in the news. Which axis of the trust radar did it dent? The links go to the book and the article. Next, module six: high-performing teams.',
  'lee/1': 'Welcome to module six. Your pilot and your reputational plan only work if a team delivers them, starting with your own pod. Begin with the Chancellor’s introduction. Then meet Candice Storey Lee, Vice Chancellor for Athletics and University Affairs and Athletic Director. She came to Vanderbilt as a student-athlete, captained the women’s basketball team, and earned three Vanderbilt degrees. She rose from an internship to lead the department in twenty twenty, in the middle of a pandemic, the first Black woman to lead an athletics department in the SEC. Under her leadership, Vanderbilt beat the number one team in the country in twenty twenty four, won its first ten-game football season in twenty twenty five, and earned the top seed in college baseball. Think about the best team you have ever been part of. What made it work? Hold that answer; you will see much of it in her approach. Her mindset fits any team on campus. As she told Sports Illustrated, some people may call it a chip on the shoulder, but if you are prepared, you feel pretty confident that you can compete. Try four fact or fiction statements. Next, the six principles behind her teams.',

  'principles/1': 'You have met the leader. Now six ideas she returns to, in her own words, from interviews and profiles; each card names its source. First, every decision is values-based, every single time, and her department’s values are integrity, leadership, resilience, passion, and competitiveness. Second, control the controllables: leaders create the conditions, and each person brings maximum effort. Third, own your response: it is okay to feel how you feel, but what matters is how you act and respond. Fourth, find the joy in the process: winning is a result, but the joy is in the commitment. Fifth, hire the leader, then back them. And sixth, your comfort comes last. As you tap each one, ask yourself a direct question: which of these does my own team already do well, and which is missing? Next, what module six means for you: for your capstone, and as a manager.',
  'principles/f1': 'Every decision, values-based. Lee says every decision she makes is values-based, every single time. Name your core values, then act on them consistently, whatever the situation.',
  'principles/f2': 'Control the controllables. In her words: it’s easy to lament things you can’t control, and we never want to do that. Leaders create the conditions for success; then it is up to each individual to give their maximum effort.',
  'principles/f3': 'Own your response. In her words: it’s okay to feel how you feel, but what really matters is what you do. You are accountable for what you do, how you act, and how you respond.',
  'principles/f4': 'Find the joy in the process. Winning is a result, she says, but the joy comes from commitment to the process, pushing yourself, and reaching your potential. A healthy culture has joy in it.',
  'principles/f5': 'Hire the leader, then back them. When she hired football coach Clark Lea in twenty twenty, she said it was about finding the right leader. She backed him through a two and ten first season, and in twenty twenty four his team upset number one Alabama.',
  'principles/f6': 'Your comfort comes last. In her words, part of being a leader is that your comfort comes last. She believes in showing up: for student-athletes, for coaches, and for alumni.',

  'teamcalls/1': 'This page is an optional go deeper. Module six gave you Candice Storey Lee’s principles in her own words. Research on teams, new to this program, complements them. Amy Edmondson of Harvard shows that teams work in one of four zones, depending on two things: the standards they hold, and their psychological safety, meaning the shared belief that it is safe to speak up, ask, and admit mistakes. Low on both is apathy. Safety without standards is comfort. Standards without safety is anxiety, where people work hard and hide problems until it is too late. High on both is the learning zone, where high-performing teams live. Leaders build safety on purpose: frame the work as learning, admit your own limits, ask real questions, and respond well to bad news. Think about your own team. Which zone is it in on a hard week? Try three situations if you want the practice, and use the links for Edmondson’s talk and Hackman’s research. Next, a check on your own pod.',
  'teamcalls/s1': 'Situation one. Your team just had its biggest win ever, and it is Monday morning. What do you do?',
  'teamcalls/s2': 'Situation two. Your best performer crossed a line in public. What do you do?',
  'teamcalls/s3': 'Situation three. A leader you hired has had a rough first year. What do you do?',

  'health/1': 'This page is also optional. You have Lee’s principles and the learning zone. Now turn them on a real team: your pod. It is a team with a deadline, which makes it a good place to practice. Google studied more than one hundred eighty of its own teams in a project called Aristotle, and found that how a team works matters more than who is on it. Five dynamics stood out. Psychological safety: it is safe to take risks with each other. Dependability: people deliver quality work on time. Structure and clarity: clear goals, roles, and plans. Meaning: the work matters to each person. And impact: people believe the work makes a difference. Safety mattered most. Think about your pod\u2019s last meeting. Did everyone speak? Rate your pod honestly on each one. The read shows your strongest dynamic and the one to work on next, with a specific action. Then ask each pod member to take it and compare in your next meeting. Next, the last part, your brief: finishing the brief.',

  'me3/1': 'Module six was high-performing teams. Here is what it means for you. For your capstone: make your pod a team, with clear roles and an owner and a date for every step. Keep your pod meetings safe to speak up in, and invite the quietest person first. And control the controllables: your effort, your preparation, and your draft, not the judges. As a manager: decide by your values, out loud, so your team learns them. Own the response; feelings are fine, but hold yourself and your team accountable for how you act and respond. And remember that your comfort comes last; show up for your people, especially when it is inconvenient. Think about the last hard call you made. Did your team know which value decided it? Write the one thing you will try in the next two weeks. Next, a short wrap-up for module six.',
  'recap3/1': 'That is module six. Three ideas from Candice Storey Lee. Values first, every time: name the values, then let them decide the hard calls. Control the controllables: leaders create the conditions, and each person brings maximum effort. And own your response: it is okay to feel how you feel, but what matters is how you act and respond. Now commit to something specific. Choose one of her principles to try with your own team next week, and write what you will actually do. Next, an optional go deeper on the research behind great teams, or go straight on to the last part, your brief: finishing the brief.',

  /* ── LESSON 4 · YOUR BRIEF ── */
  'metrics/1': 'Welcome to the last part, your brief. You have a pilot, a reputational plan, and a team. Now the second half of your brief: sections four to seven. Start with metrics, because this is where many briefs go soft, and judges notice. A strong metric has four parts. A baseline: where things are today. A target: the number you are aiming for. A date: when you will check. And it measures an outcome, not an output. Outcomes are what change for people, like days saved or students coming back. Outputs are what you produced, like emails sent or a website launched. Outputs belong in your timeline; outcomes belong in your metrics. Ask yourself the question in the headline: would you know in ninety days whether it worked? Sort six metrics, strong or weak. Next, you draft the plan.',

  'draft/1': 'You know what a strong metric looks like. Now draft sections four to seven, and notice how much you already have. Your pilot and your reputation scan fold into this draft automatically. As you type, your draft builds in the Your draft box, ready to copy for your pod. Section four is the integrated solution: what changes for people, for process, and for technology, together, just as in Lutz’s turnaround. Section five is implementation: each step with an owner role and a date, starting with your pilot. Section six is two or three strong metrics. Section seven is sustainability: who owns it after your pod disbands, how the second year is funded, and how it becomes normal work. Ask yourself the question every sponsor asks: if your pod disappeared tomorrow, who would keep this running? Open the strong example to see all four sections worked through, and read the checklist before you submit. Copy your draft into your pod’s shared document before you meet. Next, eight situations to check what you can apply.',

  'quiz/1': 'You have learned the ideas and used them on your own project. Now check whether you can apply them to situations you have not seen. Eight short scenarios, drawn from all three topics and your brief. Choose what you would do, then read the explanation, which names the idea behind the best answer. Six of eight completes the check, and you can retake it anytime. Next, your moves for the week.',

  'nextstep/1': 'You are nearly done with Course Two. This page turns the course into four moves for the week. Meet your pod for about an hour: merge your drafts, compare health checks, and set owners and dates for the final week. Finish a full first draft, all seven sections in about three pages, by Friday, November thirteenth. Post in your Teams channel and reply to a colleague; a starter post is ready to copy, built from what you wrote. Tap each move to commit. Copy the pod meeting agenda if it helps, and print this week’s takeaway, which collects your overview, your answers, and your drafts in one place. Next, the last step: how you carry all of this forward.',

  'carry/1': 'You have reached the last step of the courses, and maybe the most important one. The program ends in November. What you learned has to outlast it, and that depends on two habits. The first is to embody it. Use the tools in the open, so the people around you learn them by watching. Ask which area of focus a project serves in a planning meeting. Check the trust radar before you send a hard message. Say this is complex, so let us pilot it. The second habit is to share it. Teach one idea to your team within the next two weeks. Here is why that matters for you, not just for them: explaining an idea to others is one of the most reliable ways to keep it yourself. Researchers call it the protégé effect. And then multiply it. The vision needs more leaders who think this way, so name the next person who should be in this room. The card on this page puts the whole program on one page: the vision, strategy, brand, mission and margin, the entrepreneurial mindset, reputation, and teams. Think about your own team. Which one idea would change the most about how you work together? Now write your plan: the idea, how you will live it, how you will teach it, and who comes next. It saves here and prints in your takeaway. Next, a short close.',
  'learn/1': 'That is Course Two. Your pod now has both halves of its brief: the case from Course One, and the plan from this week, with a pilot, a reputational strategy, strong metrics, and a team ready to deliver. Week four, the week of November sixteenth, is for polishing. Your brief is due Friday, November twentieth, and three winners will be named, one in each focus area. Crescere aude. Dare to grow.'
};
